create_peak_method: 3 # this seems to work well enough

input_files:

    input_file_forMS1peaks: /Users/joewandy/Dropbox/Analysis/LDA/beer_analysis/large_study/Urine_mzXML_large_study/method_3/POS/*.mzXML
    fragmentation_file_mzML: /Users/joewandy/Dropbox/Analysis/LDA/beer_analysis/large_study/Urine_mzXML_large_study/method_3/POS/*.mzML

MS1_XCMS_peakpicking_settings:

    method: centWave
    ppm: 2
    snthresh: 3
    peakwidth_from: 5
    peakwidth_to: 100
    prefilter_from: 3
    prefilter_to: 1000
    mzdiff: 0.001
    integrate: 0
    fitgauss: FALSE
    verbose.column : TRUE

filtering_parameters_Chromatography_related:

    rt_start: 3                         # too early (top of peak)
    rt_end: 21                          # too late (top of peak)
    rt_start_before_pairing: 3          # too early (top of peak)
    rt_start_peak_before_pairing: 3     # too early (start of peak)
    rt_end_before_pairing: 21           # too late

filtering_parameters_MassSpectrometry_related:

    min_MS2_intensity: 5000
    min_MS1_intensity_wanted: 520000
    ms_msms_cut: 5000
    min_MS1_intensity : 250000

ms1_ms2_pairing_parameters:

    dppm: 10
    rt_window_from: -100
    rt_window_to: 100
    select_most_intense: TRUE
    rt_ms1_ms2_difference: 15
