create_peak_method: 1

input_files:

    fragmentation_file_m1: /Users/joewandy/Dropbox/Analysis/LDA/beer_analysis/large_study/Urine_mzXML_large_study/method_1/NEG/*.mzXML

MS1_XCMS_peakpicking_settings:

    method: centWave
    ppm: 2
    snthresh: 3
    peakwidth_from: 5
    peakwidth_to: 100
    prefilter_from: 3
    prefilter_to: 1000
    mzdiff: 0.001
    integrate: 0
    fitgauss: FALSE
    verbose.column : TRUE

filtering_parameters_Chromatography_related:

    rt_start: 3                         # too early (top of peak)
    rt_end: 21                          # too late (top of peak)

filtering_parameters_MassSpectrometry_related:

    min_MS2_intensity: 5000
    min_MS1_intensity_wanted: 260000
    min.rel.int: 0.01
    max.frags: 5000
    sn: 3
    mz_gap: 0.005
    ms_msms_cut: 5000
    min_MS1_intensity : 250000

ms1_ms2_pairing_parameters:

    cdf.corrected : FALSE
    msnSelect : precursor_int
    specFilter : specPeaks
    match.ppm : 7
    min.r : 0.75
    min.diff : 10
